# syntax=docker/dockerfile:1.7

FROM maven:3.9.11-eclipse-temurin-21 AS build
WORKDIR /workspace

ARG MODULE

COPY pom.xml ./
COPY payment-service/pom.xml payment-service/pom.xml
COPY account-service/pom.xml account-service/pom.xml
COPY ledger-service/pom.xml ledger-service/pom.xml
COPY fraud-service/pom.xml fraud-service/pom.xml
COPY auth-service/pom.xml auth-service/pom.xml
COPY gateway-service/pom.xml gateway-service/pom.xml

COPY payment-service/src payment-service/src
COPY account-service/src account-service/src
COPY ledger-service/src ledger-service/src
COPY fraud-service/src fraud-service/src
COPY auth-service/src auth-service/src
COPY gateway-service/src gateway-service/src

RUN --mount=type=cache,target=/root/.m2 \
    test -n "$MODULE" && \
    mvn -B -ntp -pl "$MODULE" -am -DskipTests package && \
    JAR="$(find "$MODULE/target" -maxdepth 1 -type f -name '*.jar' ! -name 'original-*.jar' | head -n 1)" && \
    test -n "$JAR" && \
    cp "$JAR" /workspace/app.jar

FROM eclipse-temurin:21-jre-jammy AS runtime

RUN useradd --system --uid 10001 --create-home --home-dir /home/nexapay nexapay

WORKDIR /app
COPY --from=build /workspace/app.jar /app/app.jar

USER 10001

ENTRYPOINT ["java", "-XX:MaxRAMPercentage=75.0", "-jar", "/app/app.jar"]
