server:
  port: 8081

spring:
  application:
    name: nexapay-payment-service

  datasource:
    url: jdbc:postgresql://localhost:5435/nexapay_payments
    username: nexapay
    password: nexapay

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        enable.idempotence: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

nexapay:
  outbox:
    fixed-delay-ms: 2000
