server:
  port: 8081

spring:
  application:
    name: nexapay-payment-service

  datasource:
    url: jdbc:postgresql://localhost:5435/nexapay_payments
    username: nexapay
    password: nexapay

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    template:
      observation-enabled: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        enable.idempotence: true

resilience4j:
  retry:
    instances:
      outbox-kafka:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - java.lang.IllegalStateException
  circuitbreaker:
    instances:
      outbox-kafka:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - java.lang.IllegalStateException

logging:
  file:
    name: ${NEXAPAY_LOG_DIR:logs}/nexapay-payment-service.log
  structured:
    format:
      console: logstash
      file: logstash
    json:
      add:
        service: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    propagation:
      type: w3c
    sampling:
      probability: ${NEXAPAY_TRACING_SAMPLING_PROBABILITY:1.0}
  otlp:
    tracing:
      endpoint: ${NEXAPAY_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}
  prometheus:
    metrics:
      export:
        enabled: true

nexapay:
  outbox:
    fixed-delay-ms: 2000
  security:
    jwt:
      issuer: https://nexapay.local/auth
      secret: ${NEXAPAY_JWT_SECRET:nexapay-local-dev-secret-2026-change-me}
