server:
  port: 8081

spring:
  application:
    name: nexapay-payment-service

  datasource:
    url: jdbc:postgresql://localhost:5435/nexapay_payments
    username: nexapay
    password: nexapay

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        enable.idempotence: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

nexapay:
  outbox:
    fixed-delay-ms: 2000
  security:
    jwt:
      issuer: https://nexapay.local/auth
      secret: ${NEXAPAY_JWT_SECRET:nexapay-local-dev-secret-2026-change-me}
