server:
  port: 8083

spring:
  application:
    name: nexapay-ledger-service

  datasource:
    url: jdbc:postgresql://localhost:5437/nexapay_ledger
    username: nexapay
    password: nexapay

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: nexapay-ledger-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
