server:
  port: 8082

spring:
  application:
    name: nexapay-account-service

  datasource:
    url: jdbc:postgresql://localhost:5436/nexapay_accounts
    username: nexapay
    password: nexapay

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  file:
    name: ${NEXAPAY_LOG_DIR:logs}/nexapay-account-service.log

nexapay:
  kafka:
    manage-topics: true
  outbox:
    enabled: true
    fixed-delay-ms: 2000
  security:
    jwt:
      issuer: https://nexapay.local/auth
      secret: ${NEXAPAY_JWT_SECRET:nexapay-local-dev-secret-2026-change-me}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: ${NEXAPAY_TRACING_SAMPLING_PROBABILITY:1.0}
  otlp:
    tracing:
      endpoint: ${NEXAPAY_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}
  prometheus:
    metrics:
      export:
        enabled: true
