server:
  port: 8082

spring:
  application:
    name: nexapay-account-service

  datasource:
    url: jdbc:postgresql://localhost:5436/nexapay_accounts
    username: nexapay
    password: nexapay

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
