server:
  port: 8082

spring:
  application:
    name: nexapay-account-service

  datasource:
    url: jdbc:postgresql://localhost:5436/nexapay_accounts
    username: nexapay
    password: nexapay

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

nexapay:
  kafka:
    manage-topics: true
  outbox:
    enabled: true
    fixed-delay-ms: 2000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
